mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '4.1.2'
mod 'puppetlabs-apt', '3.0.0'
mod 'puppetlabs-reboot', '4.1.0'
